version: '3.5' 
services: 
    angular-service: 
      container_name: angularcontainer  
      build: ./ 
      volumes:
        - './:/usr/src/app' 
      ports: 
        - '3500:4200' 
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"